# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - v*    
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.9]
        manylinux: [1, 2010, 2014]
        plat: [x86_64]
        include:
          - os: macos-latest
            python: 3.9
            manylinux: 1
            plat: universal2
        exclude:
          - os: macos-latest
            manylinux: 2010
          - os: macos-latest
            manylinux: 2014           
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build and test
        env:
          MB_PYTHON_VERSION: ${{ matrix.python }}
          MB_ML_VER: ${{ matrix.manylinux }}
          PLAT: ${{ matrix.plat }}
          BUILD_DEPENDS: oldest-supported-numpy
          TEST_DEPENDS: numpy
          F90WRAP_VERSION: 0.2.6
        run: |
          export PROJECT_SPEC="f90wrap==${F90WRAP_VERSION}"

          # save path to Python 3.x version
          PYTHON_DIR=$(dirname $(which python))

          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          
          # restore GitHub Actions system Python to front of path
          export PATH=${PYTHON_DIR}:$PATH
          pip install virtualenv
          
          before_install
          build_index_wheel $PROJECT_SPEC
          install_run $PLAT
          
      - name: Release wheels
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Deploy to PyPI
        if: steps.check-tag.outputs.match == 'true'
        run: |
          pip install twine
          twine upload wheelhouse/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
